name: Post Comment Initialization
on: 
  push:
      branches:
        - source
      paths:
        - 'content/posts/*'

jobs:
  label:
    name: Initialize Gitalk Comment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # fetch all history to check changed post file

      - name: get post env
        id: get_env
        run: |
          bash -x ./scripts/get_post_env.sh

      - name: new issue with above env
        uses: octokit/request-action@v2.x
        with: 
          route: POST /repos/:repository/issues
          repository: ${{ github.repository }}
          title: ${{ steps.get_env.outputs.post_name }}
          body: ${{ steps.get_env.outputs.post_url }}
          labels: '["Gitalk", ${{ steps.get_env.outputs.post_hash }} ]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
